### ISSUE TITLE
React Native - Unable to resolve 'os'

### ISSUE THREAD

**Issue by roancoetzee** [airbrake/airbrake-js#485] opened 2018-10-26 15:34 UTC
Using [this](https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-react-app/) guide from the documentation.

Import it like this 
```
import { Component } from 'react'

import AirbrakeClient from 'airbrake-js'

export default class ErrorBoundary extends Component {
  constructor(props) {
    super(props)
    this.airbrake = new AirbrakeClient({
      projectId: 1,
      projectKey: 'excluded_for_example'
    })
  }

  componentDidCatch(error, info) {
    this.airbrake.notify({
      error: error,
      params: { info: info }
    })
  }

  render() {
    return this.props.children
  }
}
```

then wrapped my `RootComponent` in `ErrorBoundary` like this
```
        <ErrorBoundary>
          <RootContainer />
        </ErrorBoundary>
```
I get the following error on both Android and iOS

```
error: bundling failed: Error: Unable to resolve module `os` from `/Users/{...}/node_modules/airbrake-js/dist/client.js`: Module `os` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/{...}/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:1306)
    at ResolutionRequest.resolveDependency (/Users/{...}/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/{...}/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/{...}/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/{...}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/{...}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/{...}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/{...}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
```
airbrake-js - 1.5.0

Any ideas?

**Comment by roancoetzee** [comment] 2018-10-30 13:30
I saw others had success with older version (0.9.0) so I tried that version of airbrake-js and I was able to get it to log errors. 

Through trial and error I found the highest version that worked for me was 1.2.0. As soon as I use 1.3.0 I got the same issue. 

Now I don't know what the issue is but looking at this [merge commit](https://github.com/airbrake/airbrake-js/commit/3352f67a5e5d595bf3cdafc56f4dc1676209826a) there were changes that involves `os` so my best guess would be to start there. 

Ill leave this issue open as it is still an issue on version 1.3.0 to 1.5.0 (at the time of writing)

**Comment by vmihailenco** [comment] 2018-11-07 08:52
Looking at https://github.com/airbrake/airbrake-js/blob/master/dist/client.js I see that `os` module is imported like this:

```js
            try {
              os = __webpack_require__(/*! os */ 'os')
            } catch (_) {}
```

Which I believe is fine. Perhaps you need to mark `os` as external module in your Webpack config - https://github.com/airbrake/airbrake-js/blob/master/webpack.config.js#L32-L49

**Comment by vmihailenco** [comment] 2018-11-30 11:46
airbrake-js uses conditional import https://github.com/airbrake/airbrake-js/blob/master/src/filter/node.ts#L5-L10. I guess react-native does not support that and I can't find what we can do about it...

**Comment by pleinonen** [comment] 2018-12-12 09:40
Reported basically same problem with Angular a while back here: https://github.com/airbrake/airbrake-js/issues/457

As you don't have access to Webpack without hacks in Angular either, I ended up adding AirbrakeJs as external script directly from the dist (angular.json, under the "scripts" section):

"node_modules/airbrake-js/dist/client.min.js",

Maybe you can do something similar in React native?

**Comment by vmihailenco** [comment] 2019-02-15 11:54
Closing as stale.

**Comment by palodelincak** [comment] 2019-03-14 16:20
This issue is still existing even with the latest 1.6.5 version. I can confirm that the 1.2.0 version works fine.

Are you going to fix this issue for upcoming versions?

**Comment by giantslogik** [comment] 2019-07-30 13:01
I forked the airbrake repo and removed the incompatible node.js detection.

npm install giantslogik/airbrake-js --save

**Comment by vmihailenco** [comment] 2019-07-30 14:36
This hopefully will be fixed in airbrake-js v2.0 - we are planning to move all node-related code to the node-airbrake package.

**Comment by giantslogik** [comment] 2019-07-31 05:40
The underlying issue is that react native does not support runtime require statements,(airbrake-js uses require, surrounded by a try catch to detect node). The require statements are evaluated at compile/packaging time in react native.

https://github.com/facebook/react-native/issues/5079

Currently the fix is to just comment out this line in node.ts
`//os = require('os');`

**Comment by vmihailenco** [comment] 2019-09-17 10:05
This should be fixed since airbrake-js was split into @airbrake/browser and @airbrake/node and there is no `os` package in @airbrake/browser any more.

**Closed by vmihailenco** 2019-09-17 10:05 UTC

**Comment by builtbyproxy** [comment] 2019-11-07 01:55
@vmihailenco By this do you mean we should use @airbrake/browser now? 
When I run this I now get unexpected errors such as `ReferenceError: window is not defined`

**Comment by vmihailenco** [comment] 2019-11-07 08:48
Use `npm install @airbrake/browser` or follow instructions from https://github.com/airbrake/airbrake-js/tree/master/packages/browser

>When I run this I now

What do you run?

**Comment by builtbyproxy** [comment] 2019-11-08 01:24
Thanks for getting back to me vmihailenco, in order to not distract the participants of this thread, lets continue this here https://github.com/airbrake/airbrake-js/issues/610
