### ISSUE TITLE
airbrake-shim : Error in console

### ISSUE THREAD

**Issue by jennyfer** [airbrake/airbrake-js#130] opened 2015-03-09 11:18 UTC
Hello,

I use airbrake-shim in a rails 3 project and am having some troubles. In FF, the console reported a `TypeError: a.document is undefined`.
In Chrome & IE10, the console reported a `Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined`.
Both referring to the airbrake.min.js file.
Could you help me please ?

**Comment by vmihailenco** [comment] 2015-03-10 07:59
That error means that `window.document` is undefined, which does not make much sense... I will take at this again later, but I don't have good ideas...

**Comment by vmihailenco** [comment] 2015-03-10 08:00
What version of the notifier do you use?

**Comment by jennyfer** [comment] 2015-03-10 08:32
I use the 3.2.1 version

**Comment by vmihailenco** [comment] 2015-03-10 08:40
That is very unlikely since latest version of the JavaScript notifier is 0.3.12. Do you load notifier from the CDN at https://ssljscdn.airbrake.io/0.3/airbrake.min.js ?

**Comment by jennyfer** [comment] 2015-03-10 08:41
yes and the error is referred to this file.

**Comment by vmihailenco** [comment] 2015-04-08 08:13
Closing since I can't reproduce it and we are changing the way we distribute notifier.

**Closed by vmihailenco** 2015-04-08 08:13 UTC
