### ISSUE TITLE
ErrorStackParser: TypeError: ErrorStackParser.parse is not a function Error: fake

### ISSUE THREAD

**Issue by cwbeck** [airbrake/airbrake-js#372] opened 2017-11-29 11:56 UTC
Using require to load this in: -

```
define(['airbrake-js', 'env'], function(AirbrakeClient, env){
    return {
        airbrakeClient: null,
        getClient: function() {
            if(this.airbrakeClient === null){
                this.airbrakeClient = new AirbrakeClient({projectId: 123, projectKey: '456'});
                this.airbrakeClient.addFilter(function(notice){
                    notice.context.environment = env.envName === 'dev'? 'development' : 'production';
                    return notice;
                });
            }
            return this.airbrakeClient;
        },
        test: function () {
            this.getClient().notify("testing error...");
        }
    };
});
```

Calling test() I get the following warning: -

ErrorStackParser: TypeError: ErrorStackParser.parse is not a function Error: fake

Any ideas? Currently using ``` "airbrake-js": "^0.9.8"```

**Comment by vmihailenco** [comment] 2017-12-19 12:38
No ideas here. Closing since I can't reproduce this.

**Closed by vmihailenco** 2017-12-19 12:38 UTC
