### ISSUE TITLE
Ready for usage in service worker?

### ISSUE THREAD

**Issue by ThomasWeiser** [airbrake/airbrake-js#398] opened 2018-02-14 18:54 UTC
Is airbrake-js ready to be used in a service worker?

As soon as I do a
```js
new AirbrakeClient({...})
```
within a service worker I get:

    Uncaught ReferenceError: window is not defined

**Comment by anmic** [comment] 2018-02-20 14:20
I tried using airbrake js client and it returned:
```
Uncaught ReferenceError: window is not defined
    at Historian.fetch (client.js:1716)
    at new Historian (client.js:1566)
    at Object.defineProperty.value (client.js:1824)
    at __webpack_require__ (client.js:31)
    at Object.defineProperty.value (client.js:481)
    at __webpack_require__ (client.js:31)
    at Object.assign.args (client.js:435)
    at __webpack_require__ (client.js:31)
    at Object.defineProperty.value (client.js:74)
    at client.js:77
```

**Comment by vmihailenco** [comment] 2018-02-20 15:53
@anmic try to add check if window is defined here - https://github.com/airbrake/airbrake-js/blob/master/src/instrumentation/historian.ts#L69, recompile airbrake-js and try again.

**Comment by vmihailenco** [comment] 2018-02-27 08:52
Hopefully fixed by https://github.com/airbrake/airbrake-js/commit/8654078b1d7e2dddfa2b85fd51b59317f3b353d8 and relesed in v1.0.6

**Closed by vmihailenco** 2018-02-27 08:52 UTC

**Comment by ntinkler-calendly** [comment] 2022-02-08 15:46
I'm seeing the current release of @airbrake/browser ("@airbrake/browser": "^2.1.7") fail in service worker environments because it uses cross-fetch, which defaults to using XHR even when fetch apis are present.  Note that XHR is not available in service worker contexts (Such as a manifest v3 chrome extension background script)

The resulting error is:
```
"ReferenceError: XMLHttpRequest is not defined
    at chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:1716:23
    at new Promise (<anonymous>)
    at fetch (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:1709:18)
    at Notifier.request$1 [as _requester] (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:1829:12)
    at Notifier._sendNotice (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:2736:19)
    at Notifier.notify (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:2718:19)
    at Notifier.notify (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:3220:38)
    at createAirbrakeClient (chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:3330:31)
    at chrome-extension://dohbfkgabajhohdidhmhhpfagifoacnk/airbrake.js:3333:1"
```

Does anyone have a way to work around the mis-behaving polyfill?

**Comment by ntinkler-calendly** [comment] 2022-02-08 17:24
Alright - A little more testing and I can confirm that it's *just* the one misbehaving cross-fetch dep that's blocking this right now.

if I simply remove the import of cross-fetch in node_modules/@airbrake/browser/esm/http_req/fetch.js
```
-    import fetch from 'cross-fetch';
```

Then I can properly report errors from the service worker context available in web extensions.
