### ISSUE TITLE
DeprecationWarning in Node 8.4.0

### ISSUE THREAD

**Issue by jpike88** [airbrake/airbrake-js#369] opened 2017-11-03 06:14 UTC
(node:34045) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
client.js:1598
(node:34045) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
client.js:1598

**Comment by vmihailenco** [comment] 2017-12-19 12:40
I don't see anything like that

```shell
> node --version
v8.9.0
> cd examples/nodejs
> node app.js
Server running on port 8080.
```

Closing since I can't reproduce this and it does not cause any problems.

**Closed by vmihailenco** 2017-12-19 12:40 UTC
